name: Build module and deploy to Cloudfront

on:
  push:
    branches:
      - "master"
secrets:
  AWS_REGION: "${{ secrets.AWS_REGION }}"
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_REGION }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_REGION }}"
  GA_PATH: "${{ secrets.GA_PATH }}"

env:
  REPO_OWNER: dev-alianwar
  REPO_NAME: ci-cd-example

jobs:
  setup:
    uses: dev-alianwar/ci-cd-example/.github/workflows/setup.yml@master
    with:
      secrets: inherit

  build:
    needs: setup
    uses: dev-alianwar/ci-cd-example/.github/workflows/build.yml@master
    with:
      dry_run: false
      is_master: true
    secrets: inherit

  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Determine branch type
      id: determine_branch
      run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

    - name: Update Version
      uses: ./.github/workflows/update-version.yml
      with:
        branch: ${{ steps.determine_branch.outputs.branch }}

  deploy:
    needs: [setup, build]
    uses: dev-alianwar/ci-cd-example/.github/workflows/deploy.yml@master
    with:
      is_master: true
      new_package_version: ${{ needs.build_module.outputs.new_package_version }}
    secrets: inherit
