name: Build module and deploy to Cloudfront

on:
  push:
    branches:
      - "master"

env:
  REPO_OWNER: dev-alianwar
  REPO_NAME: ci-cd-example

jobs:
  setup:
    uses: dev-alianwar/ci-cd-example/.github/workflows/setup.yml@master
    with:
      secrets: inherit

  build:
    needs: setup
    uses: dev-alianwar/ci-cd-example/.github/workflows/build.yml@master
    with:
      dry_run: false
      is_master: true
    secrets: inherit

  deploy:
    needs: [setup, build]
    uses: dev-alianwar/ci-cd-example/.github/workflows/deploy.yml@master
    with:
      is_master: true
      new_package_version: ${{ needs.build_module.outputs.new_package_version }}
    secrets: inherit
