name: Build module and deploy to skeleton master

on:
  push:
    branches:
      - "master"

jobs:
  setup:
    uses: dev-alianwar/ci-cd-example/.github/workflows/step-setup.yml@master
    secrets: inherit

  build_module:
    needs: setup
    secrets: inherit
    uses: dev-alianwar/ci-cd-example/.github/workflows/step-build-module.yml@master
    with:
      dry_run: false
      is_master: true

  deploy-skeleton:
    needs: [setup, build_module]
    secrets: inherit
    uses: dev-alianwar/ci-cd-example/.github/workflows/step-deploy-skeleton.yml@master
    with:
      is_master: true
      new_package_version: ${{needs.build_module.outputs.new_package_version}}
