name: Build module and deploy to Cloudfront

on:
  push:
    branches:
      - "master"

env:
  REPO: dev-alianwar/ci-cd-example

jobs:
  setup:
    uses: ${{ env.REPO }}/.github/workflows/setup.yml@master
    with:
      secrets: inherit

  build_module:
    needs: setup
    uses: ${{ env.REPO }}/.github/workflows/build-module.yml@master
    with:
      dry_run: false
      is_master: true
    secrets: inherit

  deploy-skeleton:
    needs: [setup, build_module]
    uses: ${{ env.REPO }}/.github/workflows/deploy.yml@master
    with:
      is_master: true
      new_package_version: ${{ needs.build_module.outputs.new_package_version }}
    secrets: inherit
