name: Pull request

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  setup:
    uses: dev-alianwar/ci-cd-example/.github/workflows/setup.yml@master
    secrets: inherit

  unit-tests:
    needs: setup
    secrets: inherit
    uses: dev-alianwar/ci-cd-example/.github/workflows/test.yml@master

  build_module:
    needs: [setup, unit-tests]
    secrets: inherit
    uses: dev-alianwar/ci-cd-example/.github/workflows/build.yml@master
    with:
      dry_run: true
      is_master: false
